### ISSUE TITLE
Change What Hacktoberfest to What is Open Hack Day

### ISSUE THREAD

**Issue by chamodshehanka** [GitHubExperts-LK/hacktoberfest-web#13]
We're hosting this for the 4th time
<img width="1234" alt="Screenshot 2021-09-26 at 04 33 22" src="https://user-images.githubusercontent.com/19349315/134787990-010cb098-8672-45ec-89d2-c924df885d91.png">

**Comment by jackneer** [comment]
@Shehanka I would like to do this. Please assign this to me. Thank!
